exports.elemento = {
  buttonCriarConta: 'a[href="/auth/signup/candidates"]',
  inputEmail: '#email',
  inputSenha: '#password',
  inputNome: '#displayName',
  buttonAceiteTermo: 'input[id*="privacy"]',
  buttonSubmit: 'button[type=submit]',
  inputCarreira: '.checkbox-outline',
  buttonHabilidade: '.text-muted .badge-primary',
  selectExperiencia: '.tab-content div[class="row"] div[class*="mt-3"]',
  selectMomento: 'select[id*="preferences"]',
  inputTelefone: 'input[type="tel"]',
  inputCidade: 'input[id="address.city"]',
  inputPreferenciaVaga: '.form-group .form-check',
  buttonProximo: 'button[type="button"]',
  buttonComunidade: '.active span[class*=badge-bigger]',
  selectRelacao: '.custom-select',
  inputCausasSociais: '.react-select',
  formCausaSociais: '.form-group',
  selectRaca: '#race',
  selectGenero: '#gender',
  selectOrientacaoSexual: '#sexual_orientation',
  selectDeficiencia: 'select[id*="disabilities"]',
  selectNivelConhecimento: 'span[style*="left: '
};